version: "3.8"

services:
  backend:
    build: ./backend
    container_name: bookline_backend
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_URL=postgres://bookline_user:password@db:5432/bookline_db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: bookline_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable polling for file changes
      - NODE_ENV=development

  db:
    image: postgres:latest
    container_name: bookline_db
    restart: always
    environment:
      POSTGRES_DB: bookline_db
      POSTGRES_USER: bookline_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d  # Load initial dataset

  pgadmin:
    build: ./pgadmin
    image: dpage/pgadmin4
    container_name: bookline_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bookline.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
